from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import redirect, render, get_object_or_404


class SupermarketChain(models.Model):
    NEW_WORLD = 'Nw'
    COUNTDOWN = 'Cd'
    PAK_N_SAVE = 'Ps'
    FRESH_CHOICE = 'Fc'
    WAREHOUSE = 'Wh'
    super_market_chain = [
        (NEW_WORLD , 'New World'),
        (COUNTDOWN , 'Countdown'),
        (PAK_N_SAVE , 'Pak n Save'),
        (FRESH_CHOICE , 'Fresh Choice'),
        (WAREHOUSE , 'Warehouse'),
    ]
   
    #id is autmatically generated by Django.
    chain_id = models.AutoField(primary_key=True)
    chain_name = models.CharField(
        max_length = 2,
        choices = super_market_chain,
        default = COUNTDOWN,
    )


    def __str__(self) -> str:
        return self.chain_name
    def get_absolute_url(self):
        return reverse ("chain_detail", kwargs= {"chain_id": self.pk})

class Store(models.Model):
    store_id = models.AutoField(primary_key=True)
    store_name = models.CharField(max_length=20, help_text="Must be filled in.")
    store_address = models.TextField()
    store_region = models.CharField(max_length=15, help_text="Where in NZ")
    chain_id= models.ForeignKey(SupermarketChain, on_delete=models.CASCADE, help_text="Id off the super chain.")


    def __str__(self) -> str:
        return self.store_name
    def get_absolute_url(self):
        return reverse ("store_detail", kwargs= {"store_id": self.pk})


# class Product(models.Model):
#     name = models.CharField(max_length=255)
#     price = models.DecimalField(max_digits=10, decimal_places=2)
#     description = models.TextField(blank=True, null=True)
#     # Add other fields as needed

#     def __str__(self):
#         return self.name

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=100)
    product_size = models.CharField(max_length=10)
    product_image = models.ImageField(upload_to='products/', null=True, blank=True)
    product_category = models.CharField(max_length=100)
    product_source_site = models.TextField()
    unit_type = models.CharField(max_length=10)
    product_code = models.CharField(max_length=10, unique=True)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=None)
    on_sale = models.BooleanField(null=True, default=None)
    last_updated = models.DateField(auto_now=True)
    last_checked = models.DateField(auto_now=True)
    original_unit_quantity = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=None)

    def __str__(self):
        return str(self.product_name) + ": $" + str(self.unit_price)
    def get_absolute_url(self):
        return reverse ("product_detail", kwargs= {"product_id": self.pk})

class PriceHistory(models.Model):
    price_history_id = models.AutoField(primary_key=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=None)
    date = models.DateField(auto_now_add=True)
    on_sale = models.BooleanField(null=True, default=None)
    product = models.ForeignKey(Product, to_field='product_code', on_delete=models.CASCADE)
    store= models.ForeignKey(Store, on_delete=models.CASCADE)


    def __str__(self):
        return str(self.product) + ": $" + str(self.price)
    def get_absolute_url(self):
        return reverse ("price_history_detail", kwargs= {"product_id": self.pk})

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=30, blank=True)
    # Add any other fields you want in the profile

    def __str__(self):
        return f'{self.user.username} Profile'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class UserStorePreference(models.Model):
    USP_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    store = models.ForeignKey('Store', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}'s preference for {self.store.store_name}"

    def get_absolute_url(self):
        return reverse("user_store_preference_detail", kwargs={"USP_id": self.pk})



class FavoriteProduct(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}'s favorite products: {self.product.name}"



class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    @property
    def total_price(self):
        return self.quantity * self.product.price

    def __str__(self):
        return f"{self.quantity} x {self.product.name} for {self.user.username}"
    
# def remove_from_cart(request, product_id):
#     # Retrieve the cart from the session
#     cart = request.session.get('cart', {})

#     # Convert product_id to a string since session keys are stored as strings
#     product_id_str = str(product_id)

#     if product_id_str in cart:
#         # Remove the product from the cart
#         del cart[product_id_str]
#         # Update the session
#         request.session['cart'] = cart

#     return redirect('cart')  # Redirect back to the cart page


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    # Add other fields as needed, e.g., shipping address, payment status

    def __str__(self):
        return f"Order {self.id} by {self.user.username}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.quantity} x {self.product.name} for Order {self.order.id}"