# Generated by Django 5.1 on 2024-09-09 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=25)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('unit_type', models.CharField(max_length=10)),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_sale', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(help_text='Must be filled in.', max_length=20)),
                ('store_address', models.TextField()),
                ('store_region', models.CharField(help_text='Where in NZ', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SupermarketChain',
            fields=[
                ('chain_id', models.AutoField(primary_key=True, serialize=False)),
                ('chain_name', models.CharField(choices=[('Nw', 'New World'), ('Cd', 'Countdown'), ('Ps', 'Pak n Save'), ('Fc', 'Fresh Choice'), ('Wh', 'Warehouse')], default='Cd', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('price_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('on_sale', models.BooleanField(default=None, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='chain_id',
            field=models.ForeignKey(help_text='Id off the super chain.', on_delete=django.db.models.deletion.CASCADE, to='super.supermarketchain'),
        ),
        migrations.CreateModel(
            name='UserStorePreference',
            fields=[
                ('USP_id', models.AutoField(primary_key=True, serialize=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
