# Generated by Django 5.1 on 2024-09-10 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_product_last_checked_product_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_id',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='store_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='super.store'),
            preserve_default=False,
        ),
    ]
