# Generated by Django 5.1 on 2024-09-15 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0006_rename_product_id_pricehistory_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='store_id',
            new_name='store_id_id',
        ),
    ]
