# Generated by Django 5.1 on 2024-09-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0007_rename_product_pricehistory_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='product_id',
            new_name='product',
        ),
    ]
