# Generated by Django 5.1 on 2024-09-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0008_rename_product_id_pricehistory_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='product',
            new_name='product_id',
        ),
    ]
