# Generated by Django 5.1 on 2024-09-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0009_rename_product_pricehistory_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='chain_id_id',
            new_name='chain_id',
        ),
    ]
