# Generated by Django 5.1 on 2024-09-16 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0013_alter_pricehistory_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='store_id_id',
            new_name='store',
        ),
    ]
