# Generated by Django 5.1 on 2024-09-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0014_rename_product_id_pricehistory_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
