# Generated by Django 5.1 on 2024-09-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0015_alter_pricehistory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
